import 'package:ag_flow/ag_flow.dart' show AgInject;
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

/// Generates a static accessor mixin for every class annotated with
/// [@AgInject()]:
///
///   • Classes extending any [AgBaseController] variant get a `find` getter.
///   • Classes extending [AgBaseService] or [AgStateService] get an
///     `instance` getter.
///
/// The generator emits a `mixin _$FooAgInject` into the `.g.dart` part
/// file.  The class opts in by adding `with _$FooAgInject` to its
/// declaration — a single token, no extra imports required.
///
/// Why a mixin and not a bare static in the part file?
/// Dart part files share the same library scope but cannot add new
/// *static* members to an existing class defined in another part.
/// Mixins side-step this: the class "inherits" the static from the
/// mixin's own namespace, so `Foo.find` resolves correctly.  This is
/// the same technique used by `riverpod_generator` and `injectable`.
class AgInjectGenerator extends GeneratorForAnnotation<AgInject> {
  // Controller base-class names — walking the supertype chain, any hit
  // here means the annotated class is a controller and gets `.find`.
  static const _controllerBases = {
    'AgBaseController',
    'AgListController',
    'AgDetailController',
  };

  // Service base-class names — any hit here means `.instance`.
  static const _serviceBases = {
    'AgBaseService',
    'AgStateService',
  };

  @override
  String generateForAnnotatedElement(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) {
    if (element is! ClassElement) {
      throw InvalidGenerationSourceError(
        '@AgInject() can only be applied to classes.',
        element: element,
      );
    }

    final className = element.name;
    if (className == null) {
      throw InvalidGenerationSourceError(
        '@AgInject() cannot be applied to an anonymous class.',
        element: element,
      );
    }
    final getterName = _resolveGetterName(element, className);
    return _emitMixin(className, getterName);
  }

  /// Walks [element]'s supertype chain (and mixins) to decide whether
  /// this class needs `find` (controller) or `instance` (service).
  /// Throws [InvalidGenerationSourceError] if neither base is found.
  String _resolveGetterName(ClassElement element, String className) {
    var current = element.supertype;
    while (current != null) {
      final name = current.element.name;
      if (name != null && _controllerBases.contains(name)) return 'find';
      if (name != null && _serviceBases.contains(name)) return 'instance';
      // Climb to the next supertype.
      final superElement = current.element;
      current = superElement is ClassElement ? superElement.supertype : null;
    }

    // AgListController uses a mixin — check those too.
    for (final mixin in element.mixins) {
      final name = mixin.element.name;
      if (name != null && _controllerBases.contains(name)) return 'find';
    }

    throw InvalidGenerationSourceError(
      '@AgInject() can only be placed on classes that extend '
      'AgBaseController, AgListController, AgDetailController, '
      'AgBaseService, or AgStateService. '
      '"$className" does not extend any of these.',
      element: element,
    );
  }

  /// Emits the mixin that the annotated class `with`-es.
  String _emitMixin(String className, String getterName) {
    final mixinName = '_\$${className}AgInject';
    return '''
// coverage:ignore-file

/// Generated by ag_flow_generator — do not edit by hand.
///
/// Add `with $mixinName` to [$className] to unlock:
/// ```dart
/// final x = $className.$getterName;
/// ```
mixin $mixinName {
  // ignore: library_private_types_in_public_api
  static $className get $getterName => AgLocator.find<$className>();
}
''';
  }
}
