import 'package:ag_flow_cli/src/naming/model_spec.dart';

/// Renders [spec] (and any nested classes it needs) as Dart source.
///
/// A plain, fully-owned data class — no `build_runner`, no annotations, no
/// generated part file to keep in sync. The developer owns this file from
/// the moment it lands: edit a type, add a field, delete `copyWith`, and
/// nothing regenerates over it (`ag g m` skips files that already exist).
String renderModel(ModelSpec spec) {
  final buffer = StringBuffer()
    ..writeln('// Generated by `ag g m`. This file is yours to edit —')
    ..writeln('// regenerating the module will not overwrite it.')
    ..writeln();
  for (final model in [spec, ...spec.nested]) {
    _writeClass(buffer, model);
  }
  return buffer.toString();
}

void _writeClass(StringBuffer buffer, ModelSpec spec) {
  final name = spec.className;
  final fields = spec.fields;

  buffer
    ..writeln('class $name {')
    ..writeln('  const $name({');
  for (final field in fields) {
    buffer.writeln('    required this.${field.dartName},');
  }
  buffer
    ..writeln('  });')
    ..writeln()
    ..writeln('  factory $name.fromJson(Map<String, dynamic> json) => $name(');
  for (final field in fields) {
    buffer.writeln('    ${field.dartName}: ${field.fromJsonExpression},');
  }
  buffer
    ..writeln('  );')
    ..writeln();

  for (final field in fields) {
    buffer.writeln('  final ${field.dartType} ${field.dartName};');
  }

  buffer
    ..writeln()
    ..writeln('  Map<String, dynamic> toJson() => {');
  for (final field in fields) {
    buffer.writeln("    '${field.jsonKey}': ${field.toJsonExpression},");
  }
  buffer
    ..writeln('  };')
    ..writeln()
    ..writeln('  $name copyWith({');
  for (final field in fields) {
    buffer.writeln('    ${_nullable(field.dartType)} ${field.dartName},');
  }
  buffer.writeln('  }) => $name(');
  for (final field in fields) {
    buffer.writeln(
      '    ${field.dartName}: ${field.dartName} ?? this.${field.dartName},',
    );
  }
  buffer
    ..writeln('  );')
    ..writeln('}')
    ..writeln();
}

/// A type that is already nullable must not gain a second `?`.
String _nullable(String dartType) =>
    dartType.endsWith('?') ? dartType : '$dartType?';
